project_name: git-kustomize-diff
env:
 - GO111MODULE=on
before:
  hooks:
   - go mod tidy
builds:
- main: .
  binary: git-kustomize-diff
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w
  - -X github.com/dtaniwaki/git-kustomize-diff/cmd.Version={{.Version}}
  - -X github.com/dtaniwaki/git-kustomize-diff/cmd.Revision={{.ShortCommit}}
  env:
  - CGO_ENABLED=0
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
release:
  prerelease: auto
