name: release
on:
  push:
    tags:
    - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Set up
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Check out
      uses: actions/checkout@v2
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
